version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount source code but preserve node_modules from image
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

# Named volume for node_modules
volumes:
  node_modules:
